image: haskell:latest

before_script:
    - cabal update
    - cabal install hspec
    - cabal install base

test:
    script:
        - cabal configure --enable-tests --enable-coverage
        - cabal build
        - cabal test
