image: haskell:latest

before_script:
    - cabal update
    - cabal install --only-dependencies --enable-tests

test:
    script:
        - cabal configure --enable-tests --enable-coverage
        - cabal build
        - cabal test
