language: haskell
ghc: 7.6
script:
    - cabal configure --enable-tests --enmable-library-coverage
    - cabal build
    - cabal test
after_script:
    - cabal install hpc-coveralls
    - hpc-coveralls spec
