language: haskell
ghc: 7.8.4
script:
    - cabal configure --enable-tests --enable-library-coverage
    - cabal build
    - cabal test
after_script:
    - cabal install hpc-coveralls
    - hpc-coveralls spec --repo-token $COVERALLS_TOKEN
